### ISSUE TITLE
word2vec link is broken

### ISSUE THREAD

**Issue by quinnpertuit** [loretoparisi/word2vec-twitter#1]

**Comment by loretoparisi** [comment]
@quinnpertuit1 thank you I will try to restore it asap.

**Comment by sbaktha** [comment]
Hi @loretoparisi Thank you for sharing this work. Have you restored the link yet? The link in README is still dead. Your help would be much appreciated.

**Comment by loretoparisi** [comment]
@sbaktha not yet I do not have enough Google Drive space where to load the vectors. Do you have any suggestion? Thank you.

**Comment by kyleaj** [comment]
Hi @loretoparisi! Thanks again for sharing this work. Have you considered OneDrive or Mega? Dropbox or Baidu's storage service might also work.

**Comment by loretoparisi** [comment]
@kyleaj okay thanks, I will try to upload there.

**Comment by loretoparisi** [comment]
fixed that https://github.com/loretoparisi/word2vec-twitter/blob/master/README.md#download-the-word2vec-model

**Comment by sbaktha** [comment]
Thanks @loretoparisi. The link's working now.
